CREATE DATABASE NEWIMS
USE NEWIMS

CREATE SEQUENCE CUSTSEQ
AS
INT
START WITH 1
CREATE SEQUENCE PRODSEQ
AS
INT
START WITH 1

CREATE SEQUENCE ORDSEQ
AS
INT
START WITH 1

CREATE SEQUENCE SUPSEQ
AS
INT
START WITH 1


------------------------------------------------------CUSTOMER TABLE---------------------------------------------------
CREATE TABLE CUSTOMER(
CUSTOMER_ID VARCHAR(30) PRIMARY KEY DEFAULT 'CUS'+CAST(( NEXT VALUE FOR CUSTSEQ) AS VARCHAR(3)),
CUSTOMER_NAME VARCHAR(40),
CUSTOMER_ADDR VARCHAR(40),
CUSTOMER_EMAIL VARCHAR(30)
)
INSERT INTO CUSTOMER (CUSTOMER_NAME,CUSTOMER_ADDR,CUSTOMER_EMAIL) VALUES('XYZ','LKO','XYZ@GMAIL.COM')

------------------------------------------------------ORDERS TABLE---------------------------------------------------
CREATE TABLE ORDERS(
ORDER_ID VARCHAR(30) PRIMARY KEY DEFAULT 'ORD'+CAST(( NEXT VALUE FOR ORDSEQ) AS VARCHAR(3)),
PRODUCT_ID VARCHAR(30) FOREIGN KEY REFERENCES PRODUCT(PRODUCT_ID),
CUSTOMER_ID VARCHAR(30) FOREIGN KEY REFERENCES CUSTOMER(CUSTOMER_ID),
CUSTOMER_EMAIL VARCHAR(30)
)
insert into ORDERS(PRODUCT_ID,CUSTOMER_ID,CUSTOMER_EMAIL) values('PRD3','CUS1','cus@gmail.com')
------------------------------------------------------SUPPLIER TABLE---------------------------------------------------
CREATE TABLE SUPPLIER(
SUPPLIER_ID VARCHAR(30) PRIMARY KEY DEFAULT 'SUP'+CAST(( NEXT VALUE FOR SUPSEQ) AS VARCHAR(3)),
SUPPLIER_NAME VARCHAR(40),
SUPPLIER_ADDR VARCHAR(40),
SUPPLIER_EMAIL VARCHAR(30)
)
insert into SUPPLIER (SUPPLIER_NAME,SUPPLIER_ADDR,SUPPLIER_EMAIL) values('naresh','hyd','naresh@gmail.com')

------------------------------------------------------PRODUCT TABLE---------------------------------------------------
CREATE TABLE PRODUCT(
PRODUCT_ID VARCHAR(30) PRIMARY KEY DEFAULT 'PRD'+CAST(( NEXT VALUE FOR PRODSEQ) AS VARCHAR(3)),
PRODUCT_NAME VARCHAR(40),
STOCK INT,
SUPPLIER_ID VARCHAR(30) FOREIGN KEY REFERENCES SUPPLIER(SUPPLIER_ID),
)
alter table product add PRICE int
insert into PRODUCT (PRODUCT_NAME,STOCK,SUPPLIER_ID) values('Realme',150,'SUP2')
update product set price=50000 where STOCK=150
delete from product where STOCK=100

SELECT * FROM PRODUCT
SELECT * FROM ORDERS
SELECT * FROM CUSTOMER
SELECT * FROM SUPPLIER

select supplier_id from SUPPLIER






